
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: secret-santa-api_development

 
test:
  <<: *default
  database: secret-santa-api_test


production:
  <<: *default
  database: secret-santa-api_production
  username: secret-santa-api
  password: <%= ENV["SECRET-SANTA-API_DATABASE_PASSWORD"] %>
