
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: secret-santa-api_development

 
test:
  <<: *default
  database: secret-santa-api_test


production:
  adapter: postgresql
  encoding: utf8
  database: secret_santa_api_production
  username: secret_santa_api
  password: <%= ENV["SECRET_SANTA_API_DATABASE_PASSWORD"] %>
  host: 127.0.0.1
  port: 5432
